# core/ports.py
from typing import Protocol, Iterable, Tuple, List, Optional
import numpy as np

class ModelLoaderPort(Protocol):
    def load(self, file_path: str) -> Tuple[np.ndarray, np.ndarray]:
        """Normalize uzayda (V: float32 [N,3], F: uint32 [M,3]) döner."""
        ...

class SectionComputerPort(Protocol):
    def compute(self, vertices: np.ndarray, faces: np.ndarray, pick_point: np.ndarray, axis: str) -> List[np.ndarray]:
        ...

class ViewerPort(Protocol):
    def show_mesh(self, vertices: np.ndarray, faces: np.ndarray) -> None: ...
    def clear_pick_and_sections(self) -> None: ...
    def show_pick(self, p3: Optional[np.ndarray], normal: Optional[np.ndarray]) -> None: ...
    def show_sections(self, paths: List[np.ndarray]) -> None: ...
    def set_alpha(self, a: float) -> None: ...

class SectionExporterPort(Protocol):
    def export_txt(self, paths: List[np.ndarray], file_path: str) -> None: ...
